[build]
  command = "npm run build"
  publish = "out"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[redirects]]
  from = "/privacy-policy/"
  to = "/privacy-policy"
  status = 301

[[redirects]]
  from = "/news"
  to = "/category/news/"
  status = 301

[[redirects]]
  from = "/news/"
  to = "/category/news/"
  status = 301

[[redirects]]
  from = "/*"
  to = "https://digitechlifestyle-com-206789.hostingersite.com/:splat"
  status = 200
